import type { DiscoverSettings, StockTheme, OfferBanner, HeroChip, TrendingTab } from '@shared/schema';

export interface StockCollection {
  id: string;
  slug: string;
  title: { en: string; ar: string };
  description: { en: string; ar: string };
  tickers: string[];
  heroImage?: string;
  order: number;
  status: 'active' | 'inactive';
  icon?: string;
  iconName?: string;
  isFeatured?: boolean;
}

export interface DiscoverStocksSettings {
  heroTitle: { en: string; ar: string };
  heroSubtitle: { en: string; ar: string };
  trendingTickers: string[];
  gainersTickers: string[];
  losersTickers: string[];
  featuredTickers: string[];
  showSparkline: boolean;
}

export interface BlogHomeSettings {
  featuredPostId: string;
  categoryOrder: string[];
  mostReadPostIds: string[];
}

export const mockStockThemes: StockTheme[] = [
  {
    id: '1',
    slug: 'halal-stocks',
    title_en: 'Halal Stocks',
    title_ar: 'الأسهم الحلال',
    description_en: 'Shariah-compliant stocks vetted by leading scholars',
    description_ar: 'أسهم متوافقة مع الشريعة الإسلامية معتمدة من كبار العلماء',
    tickers: ['AAPL', 'MSFT', 'GOOGL', 'NVDA', 'AMZN', 'META'],
    heroImage: '',
    icon: '🌙',
    order: 1,
    status: 'published',
    isNew: false,
    isFeatured: true,
  },
  {
    id: '2',
    slug: 'ai-semiconductors',
    title_en: 'AI & Semiconductors',
    title_ar: 'الذكاء الاصطناعي وأشباه الموصلات',
    description_en: 'Companies leading the AI and chip revolution',
    description_ar: 'الشركات الرائدة في ثورة الذكاء الاصطناعي والرقائق',
    tickers: ['NVDA', 'AMD', 'TSM', 'ASML', 'AVGO', 'INTC'],
    heroImage: '',
    icon: '🤖',
    order: 2,
    status: 'published',
    isNew: true,
    isFeatured: false,
  },
  {
    id: '3',
    slug: 'ev-mobility',
    title_en: 'EV & Mobility',
    title_ar: 'السيارات الكهربائية والتنقل',
    description_en: 'Electric vehicle and future mobility leaders',
    description_ar: 'رواد السيارات الكهربائية والتنقل المستقبلي',
    tickers: ['TSLA', 'NIO', 'RIVN', 'LCID', 'GM', 'F'],
    heroImage: '',
    icon: '🚗',
    order: 3,
    status: 'published',
    isNew: false,
    isFeatured: false,
  },
  {
    id: '4',
    slug: 'tech-giants',
    title_en: 'Tech Giants',
    title_ar: 'عمالقة التكنولوجيا',
    description_en: 'The largest technology companies by market cap',
    description_ar: 'أكبر شركات التكنولوجيا من حيث القيمة السوقية',
    tickers: ['AAPL', 'MSFT', 'AMZN', 'GOOGL', 'META', 'NFLX'],
    heroImage: '',
    icon: '💻',
    order: 4,
    status: 'published',
    isNew: false,
    isFeatured: false,
  },
  {
    id: '5',
    slug: 'fintech',
    title_en: 'Fintech & Payments',
    title_ar: 'التكنولوجيا المالية والمدفوعات',
    description_en: 'Companies transforming financial services',
    description_ar: 'الشركات التي تحول الخدمات المالية',
    tickers: ['V', 'MA', 'PYPL', 'SQ', 'JPM', 'BAC'],
    heroImage: '',
    icon: '💳',
    order: 5,
    status: 'published',
    isNew: false,
    isFeatured: false,
  },
  {
    id: '6',
    slug: 'dividend-stocks',
    title_en: 'Dividend Champions',
    title_ar: 'أبطال توزيعات الأرباح',
    description_en: 'Reliable dividend-paying stocks',
    description_ar: 'أسهم توزيعات الأرباح الموثوقة',
    tickers: ['KO', 'PEP', 'JNJ', 'PG', 'XOM', 'CVX'],
    heroImage: '',
    icon: '💰',
    order: 6,
    status: 'published',
    isNew: false,
    isFeatured: false,
  },
  {
    id: '7',
    slug: 'healthcare',
    title_en: 'Healthcare & Pharma',
    title_ar: 'الرعاية الصحية والأدوية',
    description_en: 'Leading healthcare and pharmaceutical companies',
    description_ar: 'شركات الرعاية الصحية والأدوية الرائدة',
    tickers: ['UNH', 'JNJ', 'PG', 'COST', 'WMT', 'HD'],
    heroImage: '',
    icon: '🏥',
    order: 7,
    status: 'published',
    isNew: false,
    isFeatured: false,
  },
  {
    id: '8',
    slug: 'adr-international',
    title_en: 'ADRs & International',
    title_ar: 'الإيداع الأمريكي والدولي',
    description_en: 'Access global companies through US-listed ADRs',
    description_ar: 'الوصول إلى الشركات العالمية عبر إيصالات الإيداع الأمريكية',
    tickers: ['TSM', 'ASML', 'NIO', 'BABA', 'JD', 'PDD'],
    heroImage: '',
    icon: '🌍',
    order: 8,
    status: 'published',
    isNew: true,
    isFeatured: false,
  },
  {
    id: '9',
    slug: 'etfs',
    title_en: 'ETFs',
    title_ar: 'الصناديق المتداولة',
    description_en: 'Exchange-traded funds for diversified investing',
    description_ar: 'صناديق الاستثمار المتداولة للاستثمار المتنوع',
    tickers: ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'NVDA', 'META'],
    heroImage: '',
    icon: '📊',
    order: 9,
    status: 'published',
    isNew: false,
    isFeatured: false,
  },
  {
    id: '10',
    slug: 'retail-consumer',
    title_en: 'Retail & Consumer',
    title_ar: 'التجزئة والمستهلك',
    description_en: 'Top retail and consumer goods companies',
    description_ar: 'أفضل شركات التجزئة والسلع الاستهلاكية',
    tickers: ['WMT', 'COST', 'HD', 'AMZN', 'DIS', 'NFLX'],
    heroImage: '',
    icon: '🛒',
    order: 10,
    status: 'published',
    isNew: false,
    isFeatured: false,
  },
  {
    id: '11',
    slug: 'energy',
    title_en: 'Energy & Oil',
    title_ar: 'الطاقة والنفط',
    description_en: 'Major energy and oil companies',
    description_ar: 'شركات الطاقة والنفط الكبرى',
    tickers: ['XOM', 'CVX', 'TSLA', 'GM', 'F', 'RIVN'],
    heroImage: '',
    icon: '⛽',
    order: 11,
    status: 'published',
    isNew: false,
    isFeatured: false,
  },
];

export const mockOfferBanners: OfferBanner[] = [
  {
    id: '1',
    title_en: 'Zero Commission Trading',
    title_ar: 'تداول بدون عمولة',
    subtitle_en: 'Trade US stocks with zero commission for your first 30 days',
    subtitle_ar: 'تداول الأسهم الأمريكية بدون عمولة لأول 30 يومًا',
    ctaText_en: 'Start Trading',
    ctaText_ar: 'ابدأ التداول',
    ctaUrl: '/signup',
    backgroundImage: '',
    backgroundColor: '#FF6B2C',
    placement: 'discover_offers_rail',
    status: 'active',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    order: 1,
  },
  {
    id: '2',
    title_en: 'Refer & Earn $30',
    title_ar: 'احل واكسب 30$',
    subtitle_en: 'Invite friends and earn rewards for each signup',
    subtitle_ar: 'ادعُ أصدقاءك واكسب مكافآت لكل تسجيل',
    ctaText_en: 'Invite Now',
    ctaText_ar: 'ادعُ الآن',
    ctaUrl: '/referral',
    backgroundImage: '',
    backgroundColor: '#10B981',
    placement: 'discover_offers_rail',
    status: 'active',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    order: 2,
  },
  {
    id: '3',
    title_en: 'Premium Subscription',
    title_ar: 'الاشتراك المميز',
    subtitle_en: 'Get real-time data, advanced charts & priority support',
    subtitle_ar: 'احصل على بيانات فورية ورسوم بيانية متقدمة ودعم أولوي',
    ctaText_en: 'Upgrade Now',
    ctaText_ar: 'ترقية الآن',
    ctaUrl: '/premium',
    backgroundImage: '',
    backgroundColor: '#6366F1',
    placement: 'discover_offers_rail',
    status: 'active',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    order: 3,
  },
  {
    id: '4',
    title_en: 'Learn to Invest',
    title_ar: 'تعلم الاستثمار',
    subtitle_en: 'Free courses for beginners. Start your journey today.',
    subtitle_ar: 'دورات مجانية للمبتدئين. ابدأ رحلتك اليوم.',
    ctaText_en: 'Start Learning',
    ctaText_ar: 'ابدأ التعلم',
    ctaUrl: '/blog',
    backgroundImage: '',
    backgroundColor: '#8B5CF6',
    placement: 'discover_offers_rail',
    status: 'active',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    order: 4,
  },
];

export const mockDiscoverSettings: DiscoverSettings = {
  id: '1',
  heroTitle_en: 'Discover',
  heroTitle_ar: 'اكتشف',
  heroSubtitle_en: 'Stocks, themes, and learning — in one place.',
  heroSubtitle_ar: 'الأسهم والموضوعات والتعلم — في مكان واحد.',
  heroChips: [
    { label_en: 'Trending', label_ar: 'الرائج', href: '#trending' },
    { label_en: 'Halal', label_ar: 'حلال', href: '/stocks/themes/halal-stocks' },
    { label_en: 'ETFs', label_ar: 'الصناديق المتداولة', href: '/stocks/themes/etfs' },
    { label_en: 'Beginner Guides', label_ar: 'أدلة المبتدئين', href: '/blog?category=beginners' },
    { label_en: 'Offers', label_ar: 'العروض', href: '#offers' },
  ],
  featuredThemeNewSlug: 'adr-international',
  featuredThemeMonthSlug: 'halal-stocks',
  otherThemeSlugs: ['ai-semiconductors', 'ev-mobility', 'tech-giants', 'fintech', 'dividend-stocks', 'healthcare'],
  trendingTabs: [
    { key: 'gainers', label_en: 'Gainers', label_ar: 'الرابحون', tickers: ['NVDA', 'RIVN', 'AMD', 'META', 'XOM', 'CVX', 'JPM', 'BAC'] },
    { key: 'losers', label_en: 'Losers', label_ar: 'الخاسرون', tickers: ['NIO', 'LCID', 'PYPL', 'INTC', 'NFLX', 'PEP', 'AVGO'] },
    { key: 'most_watched', label_en: 'Most Watched', label_ar: 'الأكثر متابعة', tickers: ['TSLA', 'AAPL', 'NVDA', 'MSFT', 'GOOGL', 'AMZN', 'META'] },
  ],
  featuredTickers: ['AAPL', 'TSLA', 'NVDA', 'MSFT', 'GOOGL', 'AMZN', 'META', 'AMD', 'NFLX', 'DIS', 'V', 'JPM'],
  learnFeaturedPostId: '1',
  learnSecondaryPostIds: ['2', '3'],
  learnCategorySlugs: ['education', 'analysis', 'strategy', 'beginners'],
  sectionVisibility: {
    offers: true,
    themes: true,
    trending: true,
    featured: true,
    priceAlerts: true,
    learn: true,
    newsletter: true,
    disclosures: true,
  },
};

export const mockStockCollections: StockCollection[] = [
  {
    id: '1',
    slug: 'halal-stocks',
    title: { en: 'Halal Stocks', ar: 'الأسهم الحلال' },
    description: { en: 'Explore shares that may align with Shariah screening approaches', ar: 'استكشف الأسهم التي قد تتوافق مع معايير الفحص الشرعي' },
    tickers: ['AAPL', 'MSFT', 'GOOGL', 'NVDA', 'AMZN', 'META', 'TSLA', 'V', 'MA', 'JNJ', 'PG', 'KO'],
    order: 1,
    status: 'active',
    icon: '🌙',
    iconName: 'Moon',
    isFeatured: true,
  },
  {
    id: '2',
    slug: 'ai-semiconductors',
    title: { en: 'AI & Semiconductors', ar: 'الذكاء الاصطناعي وأشباه الموصلات' },
    description: { en: 'Companies leading the AI and chip revolution', ar: 'الشركات الرائدة في ثورة الذكاء الاصطناعي والرقائق' },
    tickers: ['NVDA', 'AMD', 'TSM', 'ASML', 'AVGO', 'INTC'],
    order: 2,
    status: 'active',
    icon: '🤖',
    iconName: 'Cpu',
  },
  {
    id: '3',
    slug: 'ev-mobility',
    title: { en: 'EV & Mobility', ar: 'السيارات الكهربائية والتنقل' },
    description: { en: 'Electric vehicle and future mobility leaders', ar: 'رواد السيارات الكهربائية والتنقل المستقبلي' },
    tickers: ['TSLA', 'NIO', 'RIVN', 'LCID', 'GM', 'F'],
    order: 3,
    status: 'active',
    icon: '🚗',
    iconName: 'Car',
  },
  {
    id: '4',
    slug: 'tech-giants',
    title: { en: 'Tech Giants', ar: 'عمالقة التكنولوجيا' },
    description: { en: 'The largest technology companies by market cap', ar: 'أكبر شركات التكنولوجيا من حيث القيمة السوقية' },
    tickers: ['AAPL', 'MSFT', 'AMZN', 'GOOGL', 'META', 'NFLX'],
    order: 4,
    status: 'active',
    icon: '💻',
    iconName: 'Monitor',
  },
  {
    id: '5',
    slug: 'fintech',
    title: { en: 'Fintech & Payments', ar: 'التكنولوجيا المالية والمدفوعات' },
    description: { en: 'Companies transforming financial services', ar: 'الشركات التي تحول الخدمات المالية' },
    tickers: ['V', 'MA', 'PYPL', 'SQ', 'JPM', 'BAC'],
    order: 5,
    status: 'active',
    icon: '💳',
    iconName: 'CreditCard',
  },
  {
    id: '6',
    slug: 'dividend-stocks',
    title: { en: 'Dividend Champions', ar: 'أبطال توزيعات الأرباح' },
    description: { en: 'Reliable dividend-paying stocks', ar: 'أسهم توزيعات الأرباح الموثوقة' },
    tickers: ['KO', 'PEP', 'JNJ', 'PG', 'XOM', 'CVX'],
    order: 6,
    status: 'active',
    icon: '💰',
    iconName: 'Coins',
  },
  {
    id: '7',
    slug: 'healthcare',
    title: { en: 'Healthcare & Pharma', ar: 'الرعاية الصحية والأدوية' },
    description: { en: 'Leading healthcare and pharmaceutical companies', ar: 'شركات الرعاية الصحية والأدوية الرائدة' },
    tickers: ['UNH', 'JNJ', 'PG', 'COST', 'WMT', 'HD'],
    order: 7,
    status: 'active',
    icon: '🏥',
    iconName: 'Heart',
  },
  {
    id: '8',
    slug: 'retail-consumer',
    title: { en: 'Retail & Consumer', ar: 'التجزئة والمستهلك' },
    description: { en: 'Top retail and consumer goods companies', ar: 'أفضل شركات التجزئة والسلع الاستهلاكية' },
    tickers: ['WMT', 'COST', 'HD', 'AMZN', 'DIS', 'NFLX'],
    order: 8,
    status: 'active',
    icon: '🛒',
    iconName: 'ShoppingCart',
  },
  {
    id: '9',
    slug: 'energy',
    title: { en: 'Energy & Oil', ar: 'الطاقة والنفط' },
    description: { en: 'Major energy and oil companies', ar: 'شركات الطاقة والنفط الكبرى' },
    tickers: ['XOM', 'CVX', 'TSLA', 'GM', 'F', 'RIVN'],
    order: 9,
    status: 'active',
    icon: '⛽',
    iconName: 'Fuel',
  },
];

export const mockDiscoverStocksSettings: DiscoverStocksSettings = {
  heroTitle: {
    en: 'Discover stocks',
    ar: 'اكتشف الأسهم',
  },
  heroSubtitle: {
    en: 'Explore popular companies and market themes',
    ar: 'استكشف الشركات الشائعة وموضوعات السوق',
  },
  trendingTickers: ['TSLA', 'NVDA', 'AAPL', 'AMZN', 'MSFT', 'GOOGL', 'META', 'AMD'],
  gainersTickers: ['NVDA', 'RIVN', 'AMD', 'META', 'XOM', 'CVX', 'JPM', 'BAC'],
  losersTickers: ['NIO', 'LCID', 'PYPL', 'INTC', 'NFLX', 'PEP', 'AVGO', 'TSLA'],
  featuredTickers: ['AAPL', 'TSLA', 'NVDA', 'MSFT', 'GOOGL', 'AMZN', 'META', 'AMD', 'NFLX', 'DIS', 'V', 'JPM'],
  showSparkline: true,
};

export const mockBlogHomeSettings: BlogHomeSettings = {
  featuredPostId: '2',
  categoryOrder: ['Education', 'Analysis', 'Strategy', 'News'],
  mostReadPostIds: ['1', '2', '3'],
};

export const blogCategories = [
  { id: 'education', name: { en: 'Education', ar: 'التعليم' }, slug: 'education' },
  { id: 'analysis', name: { en: 'Analysis', ar: 'التحليل' }, slug: 'analysis' },
  { id: 'strategy', name: { en: 'Strategy', ar: 'الاستراتيجية' }, slug: 'strategy' },
  { id: 'news', name: { en: 'News', ar: 'الأخبار' }, slug: 'news' },
  { id: 'beginners', name: { en: 'Beginner Guides', ar: 'أدلة المبتدئين' }, slug: 'beginners' },
  { id: 'etfs', name: { en: 'ETFs', ar: 'الصناديق المتداولة' }, slug: 'etfs' },
];

export { type DiscoverSettings, type StockTheme, type OfferBanner, type HeroChip, type TrendingTab };
